apiVersion: v1
kind: Pod
metadata:
  name: marp
  labels:
    app: marp
spec:
  containers:
  - image: robinhoodis/marp:0.1.9
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: Always
    name: marp
  restartPolicy: Always
